/*
  DANTE JETER WEBSITE — VERSION 18.2 MASTER PROPERTY CONFIGURATION

  THIS IS THE ONE FILE TO EDIT FOR PROPERTY CHANGES.
  Update price, status, address, facts, descriptions, page links, and photos here.
  The homepage, listings page, individual property pages, and related listings
  are generated from this master data.
*/

window.MASTER_PROPERTIES = {
  "104-paul-avenue": {
    id: "104-paul-avenue",
    version: "19.8",
    status: "Under Contract",
    featured: true,
    featuredOrder: 2,
    community: "Weirton",
    type: "Residential",
    address: "104 Paul Avenue",
    cityStateZip: "Weirton, WV 26062",
    price: 214000,
    beds: 3,
    baths: 2,
    sqft: "1,060",
    mls: "5209131",
    summary: "A versatile three-bedroom property with a rear dwelling, detached garage, deck, and flexible living options.",
    headline: "Two Homes. One Remarkably Versatile Property.",
    heroDescription: "Comfortable living, added flexibility, and potential income opportunity—all within one distinctive Weirton property.",
    page: "property-showcase.html",
    assetBase: "assets/104-paul-avenue",
    hero: "hero.jpg",
    video: "walkthrough.mp4",
    videoPoster: "video-poster.jpg",
    detailFacts: [
      { value: "3", label: "Beds" },
      { value: "2", label: "Baths" },
      { value: "1,060", label: "Front Sq. Ft." }
    ],
    photos: [
      { file: "photo-01.jpg", alt: "Front exterior" },
      { file: "photo-02.jpg", alt: "Front exterior angle" },
      { file: "photo-03.jpg", alt: "Entry and foyer" },
      { file: "photo-04.jpg", alt: "Living room" },
      { file: "photo-05.jpg", alt: "Living room alternate view" },
      { file: "photo-06.jpg", alt: "Dining area" },
      { file: "photo-07.jpg", alt: "Kitchen" },
      { file: "photo-08.jpg", alt: "Bedroom one" },
      { file: "photo-09.jpg", alt: "Bedroom two" },
      { file: "photo-10.jpg", alt: "Bedroom three" },
      { file: "photo-11.jpg", alt: "Bathroom" },
      { file: "photo-12.jpg", alt: "Rear deck" },
      { file: "photo-13.jpg", alt: "Detached garage" },
      { file: "photo-14.jpg", alt: "Rear dwelling" },
      { file: "photo-15.jpg", alt: "Rear exterior and yard" },
      { file: "photo-16.jpg", alt: "Aerial property view" },
      { file: "photo-17.jpg", alt: "Aerial neighborhood view" }
    ]
  },

  "333-patricia-avenue": {
    id: "333-patricia-avenue",
    version: "19.8",
    status: "Sold",
    featured: false,
    featuredOrder: 2,
    community: "Weirton",
    type: "Residential",
    address: "333 Patricia Avenue",
    cityStateZip: "Weirton, WV",
    price: 139000,
    beds: 3,
    baths: 1.5,
    sqft: "—",
    acres: "0.18",
    mls: "5229159",
    style: "Split-level",
    attachedGarage: "1-car",
    detachedGarage: "Approximately 2.5-car",
    outdoorSpace: "Large rear deck",
    laundry: "Dedicated laundry area",
    propertyType: "Single-family residence",
    locationLabel: "Weirton, West Virginia",
    summary: "A well-maintained split-level home with three bedrooms, one and a half baths, a large rear deck, and exceptional garage space.",
    headline: "Comfortable Living. Exceptional Garage Space.",
    heroDescription: "A well-maintained split-level home with flexible living spaces, a large rear deck, and outstanding attached and detached garage capacity.",
    page: "333-patricia-avenue.html",
    assetBase: "assets/333-patricia-avenue",
    hero: "hero.jpg",
    detailFacts: [
      { value: "3", label: "Beds" },
      { value: "1.5", label: "Baths" },
      { value: "0.18", label: "Acres" }
    ],
    photos: [
      { file: "photo-01.jpg", alt: "Front exterior of 333 Patricia Avenue" },
      { file: "photo-02.jpg", alt: "Front exterior angle showing the attached and detached garages" },
      { file: "photo-03.jpg", alt: "Distinctive covered front entry" },
      { file: "photo-04.jpg", alt: "Living room with hardwood floors and a large front window" },
      { file: "photo-05.jpg", alt: "Living room alternate view with hardwood floors" },
      { file: "photo-06.jpg", alt: "Dining room with hardwood flooring" },
      { file: "photo-07.jpg", alt: "Dining area with views into the kitchen and living room" },
      { file: "photo-08.jpg", alt: "Kitchen with abundant wood cabinetry" },
      { file: "photo-09.jpg", alt: "Upper hallway and split-level entry" },
      { file: "photo-10.jpg", alt: "Full bathroom with glass shower enclosure" },
      { file: "photo-11.jpg", alt: "Bedroom with double closet and ceiling fan" },
      { file: "photo-12.jpg", alt: "Bedroom with blue carpet and double closet" },
      { file: "photo-13.jpg", alt: "Lower-level recreation room" },
      { file: "photo-14.jpg", alt: "Rear and side exterior with driveway access" },
      { file: "photo-15.jpg", alt: "Large rear deck overlooking the yard" },
      { file: "photo-16.jpg", alt: "Spacious detached garage exterior" },
      { file: "photo-17.jpg", alt: "Front exterior at dusk" }
    ]
  },

  "1716-cameron-hollow-road": {
    id: "1716-cameron-hollow-road",
    version: "17.2",
    status: "Under Contract",
    featured: true,
    featuredOrder: 3,
    community: "New Cumberland",
    type: "Residential",
    address: "1716 Cameron Hollow Road",
    cityStateZip: "New Cumberland, WV 26047",
    price: 295000,
    beds: 3,
    baths: 1.5,
    sqft: "2,054",
    acres: "1.15",
    mls: "5221351",
    style: "Split-level",
    yearBuilt: "1974",
    attachedGarage: "2-car",
    detachedGarage: "—",
    outdoorSpace: "Concrete patio, mature trees, and storage building",
    laundry: "Lower-level laundry room",
    propertyType: "Single-family residence",
    locationLabel: "New Cumberland, West Virginia",
    heating: "Forced air",
    cooling: "Central air",
    water: "Public",
    sewer: "Septic",
    fireplace: "1 brick fireplace",
    summary: "A spacious three-bedroom split-level on 1.15 acres with 2,054 finished square feet, a two-car garage, mature trees, and expansive outdoor living space.",
    headline: "Country Comfort. Space to Live Well.",
    heroDescription: "A thoughtfully maintained split-level home with 2,054 finished square feet, flexible living areas, a two-car garage, Generac backup power, and 1.15 scenic acres in New Cumberland.",
    marketingRemarks: "Step inside 1716 Cameron Hollow Road, New Cumberland, WV, and you\u2019re welcomed by an open foyer featuring premium LVP flooring that leads into a comfortable living room with a brick fireplace, anchored by a live-edge wood mantle, a wood accent wall, and recessed lighting throughout. The adjoining dining room adds character with a full-room chair molding, crown molding, and a warm view into the main living space. The kitchen offers hardwood flooring, premium soft-close cabinetry, pocket pull-out storage, detailed cabinet trim, tile backsplash, and pocket doors for added functionality. This split-level home includes 3 bedrooms and 1.5 baths, along with a lower-level recreational room and a laundry room that provides additional usable space. The lower level features a breezeway with sliding doors, offering convenient exterior access and also connects the home to the 2-car garage. The outdoor areas include a covered front porch, a concrete patio, a large open yard, mature trees, a storage building, and a new asphalt driveway in front of the home. Supported by a Generac 20kW generator with an automatic transfer switch, this property offers a strong combination of comfort, utility, storage, and country appeal on 1+ acres in New Cumberland.",
    page: "1716-cameron-hollow-road.html",
    assetBase: "assets/1716-cameron-hollow-road",
    hero: "hero.jpg",
    detailFacts: [
      { value: "3", label: "Beds" },
      { value: "1.5", label: "Baths" },
      { value: "2,054", label: "Sq. Ft." }
    ],
    floorPlans: [
      { file: "photo-41.jpg", alt: "Combined floor plan overview" },
      { file: "photo-42.jpg", alt: "Main living level floor plan" },
      { file: "photo-43.jpg", alt: "Upper bedroom level floor plan" },
      { file: "photo-44.jpg", alt: "Lower level and garage floor plan" }
    ],
    photos: [
      { file: "photo-01.jpg", alt: "Aerial front exterior and driveway" },
      { file: "photo-02.jpg", alt: "Front exterior with attached two-car garage" },
      { file: "photo-03.jpg", alt: "Rear and side brick exterior" },
      { file: "photo-04.jpg", alt: "Covered front porch and attached garage" },
      { file: "photo-05.jpg", alt: "Covered front entry" },
      { file: "photo-06.jpg", alt: "Open foyer with brick accent wall" },
      { file: "photo-07.jpg", alt: "Foyer and stairway" },
      { file: "photo-08.jpg", alt: "Living room with brick fireplace" },
      { file: "photo-09.jpg", alt: "Living room fireplace and wood accent wall" },
      { file: "photo-10.jpg", alt: "Living room adjoining dining area" },
      { file: "photo-11.jpg", alt: "Dining room with chair molding" },
      { file: "photo-12.jpg", alt: "Dining room alternate view" },
      { file: "photo-13.jpg", alt: "Kitchen with premium cabinetry" },
      { file: "photo-14.jpg", alt: "Kitchen cabinetry and tile backsplash" },
      { file: "photo-15.jpg", alt: "Kitchen workspace and window" },
      { file: "photo-16.jpg", alt: "Kitchen refrigerator wall" },
      { file: "photo-17.jpg", alt: "Full bathroom" },
      { file: "photo-18.jpg", alt: "Primary bedroom" },
      { file: "photo-19.jpg", alt: "Primary bedroom alternate view" },
      { file: "photo-20.jpg", alt: "Second bedroom" },
      { file: "photo-21.jpg", alt: "Second bedroom alternate view" },
      { file: "photo-22.jpg", alt: "Third bedroom" },
      { file: "photo-23.jpg", alt: "Third bedroom alternate view" },
      { file: "photo-24.jpg", alt: "Lower-level family room" },
      { file: "photo-25.jpg", alt: "Lower-level recreation room alternate view" },
      { file: "photo-26.jpg", alt: "Breezeway with sliding doors" },
      { file: "photo-27.jpg", alt: "Half bathroom" },
      { file: "photo-28.jpg", alt: "Laundry and utility room" },
      { file: "photo-29.jpg", alt: "Rear patio and landscaping" },
      { file: "photo-30.jpg", alt: "Spacious concrete patio" },
      { file: "photo-31.jpg", alt: "Backyard and mature trees" },
      { file: "photo-32.jpg", alt: "Storage building and yard" },
      { file: "photo-33.jpg", alt: "Rear exterior with attached garage" },
      { file: "photo-34.jpg", alt: "Aerial property and countryside" },
      { file: "photo-35.jpg", alt: "Aerial front property view" },
      { file: "photo-36.jpg", alt: "Top-down aerial parcel view" },
      { file: "photo-37.jpg", alt: "Regional aerial view with property marker" },
      { file: "photo-38.jpg", alt: "Regional aerial view toward nearby farmland" },
      { file: "photo-39.jpg", alt: "Twilight front exterior" },
      { file: "photo-40.jpg", alt: "Combined floor plan overview" },
      { file: "photo-41.jpg", alt: "Main living level floor plan" },
      { file: "photo-42.jpg", alt: "Upper bedroom level floor plan" },
      { file: "photo-43.jpg", alt: "Lower level and garage floor plan" },
      { file: "photo-44.jpg", alt: "Top-down aerial view of home and lot" }
    ]
  },


  "3717-orchard-street": {
    id: "3717-orchard-street",
    version: "19.7.1",
    status: "Active",
    featured: true,
    featuredOrder: 4,
    community: "Weirton",
    type: "Residential Income",
    address: "3717 Orchard Street",
    cityStateZip: "Weirton, WV 26062",
    price: 49000,
    beds: 4,
    baths: 2,
    sqft: "1,566",
    acres: "0.05",
    mls: "5237807",
    style: "Up-and-down duplex",
    yearBuilt: "1920",
    attachedGarage: "No garage",
    outdoorSpace: "Covered front porch",
    laundry: "No dedicated laundry listed",
    propertyType: "Residential income duplex",
    locationLabel: "Weirton, West Virginia",
    heating: "Forced air",
    cooling: "None",
    water: "Public",
    sewer: "Public",
    fireplace: "Not listed",
    summary: "An affordable up-and-down duplex with a one-bedroom main-level unit, a three-bedroom upper unit, two full baths, and separate gas and electric service.",
    headline: "Two Units. One Accessible Investment Opportunity.",
    heroDescription: "A 1,566-square-foot Weirton duplex offering flexible income potential at an approachable price point.",
    marketingRemarks: "Opportunity awaits at 3717 Orchard Street. Priced at $49,000, this up-and-down duplex offers an affordable opportunity to add a multifamily property to an investment portfolio. The main-level unit features one bedroom and one full bath, while the upper-level unit offers three bedrooms and one full bath. Situated on approximately 0.05 acres, the property features forced-air heating and driveway parking. Gas and electric service are separate; the water meter is shared. Whether you are expanding a rental portfolio or exploring owner-occupancy possibilities, 3717 Orchard Street offers an attractive price point with plenty of potential.",
    page: "3717-orchard-street.html",
    assetBase: "assets/3717-orchard-street",
    hero: "hero.jpg",
    detailFacts: [
      { value: "4", label: "Total Beds" },
      { value: "2", label: "Baths" },
      { value: "1,566", label: "Sq. Ft." }
    ],
    photos: [
      { file: "photo-01.jpg", alt: "Front exterior of 3717 Orchard Street" },
      { file: "photo-02.jpg", alt: "Wide front exterior and neighborhood setting" },
      { file: "photo-03.jpg", alt: "Front exterior from Orchard Street" },
      { file: "photo-04.jpg", alt: "Side exterior and utility connections" },
      { file: "photo-05.jpg", alt: "Rear exterior of the duplex" },
      { file: "photo-06.jpg", alt: "Covered rear entry" },
      { file: "photo-07.jpg", alt: "Interior living space with natural light" },
      { file: "photo-08.jpg", alt: "Interior room with hardwood flooring" },
      { file: "photo-09.jpg", alt: "Spacious interior room" },
      { file: "photo-10.jpg", alt: "Full bathroom" },
      { file: "photo-11.jpg", alt: "Kitchen with dark cabinetry" },
      { file: "photo-12.jpg", alt: "Interior hallway" },
      { file: "photo-13.jpg", alt: "Additional side exterior view" }
    ]
  },


  "3928-hanlin-way": {
    id: "3928-hanlin-way",
    version: "18.3",
    status: "Under Contract",
    featured: true,
    featuredOrder: 7,
    community: "Weirton",
    type: "Residential",
    address: "3928 Hanlin Way",
    cityStateZip: "Weirton, WV 26062",
    price: 174900,
    beds: 4,
    baths: 2,
    sqft: "1,686",
    acres: "0.17",
    mls: "5172288",
    style: "Cape Cod",
    yearBuilt: "1952",
    attachedGarage: "1-car",
    outdoorSpace: "Manageable yard with storage shed",
    laundry: "Lower-level laundry room",
    propertyType: "Single-family residence",
    locationLabel: "Weirton, West Virginia",
    heating: "Forced air",
    cooling: "Central air",
    water: "Public",
    sewer: "Public",
    fireplace: "No",
    roof: "Steel roof installed in 2023",
    electrical: "200-amp service",
    basement: "Finished walk-out lower level",
    summary: "A move-in-ready four-bedroom Cape Cod with two full baths, a main-floor primary suite, finished walk-out lower level, attached garage, and a newer steel roof.",
    headline: "Thoughtfully Updated. Flexible Across Three Levels.",
    heroDescription: "A well-maintained Cape Cod with 1,686 finished square feet, a main-floor primary suite, updated kitchen, finished walk-out lower level, and meaningful recent improvements.",
    marketingRemarks: "Discover this well-maintained four-bedroom, two-bath Cape Cod on Hanlin Way in Weirton. The move-in-ready home features a main-floor primary suite with a private bath, an updated kitchen, and a bright living area. A finished walk-out lower level adds two additional bedrooms, a laundry room, and flexible space for work, guests, hobbies, or storage. Recent upgrades include a steel roof installed in 2023, a newer furnace and central air system, and 200-amp electrical service. An attached one-car garage, manageable yard, storage shed, and convenient access to shopping, schools, and major routes complete the offering.",
    page: "3928-hanlin-way.html",
    assetBase: "assets/3928-hanlin-way",
    hero: "hero.jpg",
    detailFacts: [
      { value: "4", label: "Beds" },
      { value: "2", label: "Baths" },
      { value: "1,686", label: "Sq. Ft." }
    ],
    photos: [
      { file: "photo-01.jpg", alt: "Front exterior of 3928 Hanlin Way" },
      { file: "photo-02.jpg", alt: "Angled exterior showing the steel roof and attached garage" },
      { file: "photo-03.jpg", alt: "Covered front entry and porch detail" },
      { file: "photo-04.jpg", alt: "Bright living room with updated flooring" },
      { file: "photo-05.jpg", alt: "Living room alternate view toward the kitchen" },
      { file: "photo-06.jpg", alt: "Updated kitchen with oak cabinetry and stainless appliances" },
      { file: "photo-07.jpg", alt: "Dining area with open connection to the kitchen" },
      { file: "photo-08.jpg", alt: "Main-level full bathroom" },
      { file: "photo-09.jpg", alt: "Upper-level bedroom with personalized decor" },
      { file: "photo-10.jpg", alt: "Finished lower-level flex or office space" },
      { file: "photo-11.jpg", alt: "Large finished lower-level bedroom" },
      { file: "photo-12.jpg", alt: "Lower-level bedroom alternate view" },
      { file: "photo-13.jpg", alt: "Laundry and utility room" },
      { file: "photo-14.jpg", alt: "Rear aerial view of the property and storage shed" },
      { file: "photo-15.jpg", alt: "Front aerial view within the Hanlin Way neighborhood" },
      { file: "photo-16.jpg", alt: "Top-down aerial view of the home and lot" },
      { file: "photo-17.jpg", alt: "Regional aerial view highlighting the neighborhood setting" },
      { file: "photo-18.jpg", alt: "Rustic full bathroom with wood-plank walls" },
      { file: "photo-19.jpg", alt: "Main-floor primary bedroom" }
    ]
  },


  "300-pennsylvania-avenue": {
    id: "300-pennsylvania-avenue",
    version: "18.1",
    status: "Active",
    featured: true,
    featuredOrder: 5,
    community: "Weirton",
    type: "Commercial",
    propertyType: "Commercial Sale",
    subtype: "Mixed Use",
    address: "300 Pennsylvania Avenue",
    cityStateZip: "Weirton, WV 26056",
    price: 130000,
    acres: "0.38",
    yearBuilt: "1968",
    mls: "5214546",
    currentUse: "Daily Mechanics",
    heating: "Other",
    structures: "One commercial building",
    bays: "3 drive-in bays",
    restrooms: "2 restrooms",
    officeSpace: "Dedicated office and customer area",
    parking: "Ample on-site parking",
    frontage: "Strong Pennsylvania Avenue visibility",
    summary: "A versatile former service station on approximately 0.38 acres with three garage bays, office space, two restrooms, and extensive on-site parking.",
    headline: "A High-Visibility Commercial Canvas.",
    heroDescription: "Position your next business on Pennsylvania Avenue with a three-bay automotive facility, flexible workspace, customer-facing office area, and redevelopment potential.",
    marketingRemarks: "Positioned on approximately 0.38 acres, this former gas station property offers a distinctive opportunity for entrepreneurs, investors, and business owners seeking a highly adaptable commercial site. The building provides a spacious three-bay garage layout, an office and customer area, and two restrooms. Generous parking in front and alongside the building supports convenient customer and employee access. Its visible Pennsylvania Avenue location and flexible footprint may suit automotive users, contractors, storage operations, service businesses, retail conversion concepts, or redevelopment, subject to local zoning and permitted-use requirements. Buyers should complete independent due diligence regarding zoning, environmental considerations, permitted uses, and future development plans.",
    investmentHighlights: [
      "Three drive-in service bays with open work areas",
      "Office and customer reception space",
      "Two restrooms and practical service layout",
      "Approximately 0.38 acres with ample parking",
      "Strong visibility along Pennsylvania Avenue",
      "Potential for automotive, contractor, storage, service, retail, or redevelopment uses"
    ],
    useCases: ["Automotive service", "Contractor headquarters", "Equipment or vehicle storage", "Service-based business", "Retail conversion", "Redevelopment opportunity"],
    page: "300-pennsylvania-avenue.html",
    assetBase: "assets/300-pennsylvania-avenue",
    hero: "hero.jpg",
    detailFacts: [
      { value: "3", label: "Drive-In Bays" },
      { value: "0.38", label: "Acres" },
      { value: "1968", label: "Year Built" }
    ],
    photos: [
      { file: "photo-01.jpg", alt: "Front exterior and parking area at 300 Pennsylvania Avenue" },
      { file: "photo-02.jpg", alt: "Angled front exterior of the commercial building" },
      { file: "photo-03.jpg", alt: "Side exterior and storefront windows" },
      { file: "photo-04.jpg", alt: "Wide view of the site and parking area" },
      { file: "photo-05.jpg", alt: "Storefront and service-bay exterior" },
      { file: "photo-06.jpg", alt: "Office and customer reception area" },
      { file: "photo-07.jpg", alt: "Alternate view of the office and waiting area" },
      { file: "photo-08.jpg", alt: "Three-bay automotive work area" },
      { file: "photo-09.jpg", alt: "Automotive service area with vehicle lift" },
      { file: "photo-10.jpg", alt: "Vehicle lift and work bays" },
      { file: "photo-11.jpg", alt: "Side exterior and garage access" },
      { file: "photo-12.jpg", alt: "Wide interior service-bay view" },
      { file: "photo-13.jpg", alt: "Twilight exterior of 300 Pennsylvania Avenue" }
    ]
  },

  "1130-north-chester-street": {
    id: "1130-north-chester-street",
    version: "18.1",
    status: "Active",
    featured: true,
    featuredOrder: 6,
    community: "New Cumberland",
    type: "Commercial",
    propertyType: "Commercial Sale",
    subtype: "Mixed Use",
    address: "1130 North Chester Street",
    cityStateZip: "New Cumberland, WV 26047",
    price: 170000,
    acres: "0.30",
    yearBuilt: "1990",
    mls: "5218759",
    currentUse: "Vacant",
    heating: "Oil",
    structures: "Two buildings across three parcels",
    bays: "4 drive-in bays",
    restrooms: "Restrooms in both buildings",
    officeSpace: "Garage office plus separate restaurant-style building",
    parking: "Expansive paved site area",
    frontage: "Route 2 visibility near the Route 8 intersection",
    summary: "A two-building mixed-use commercial property across three parcels with a four-bay garage, lifts, offices, restrooms, and a separate drive-thru-capable building.",
    headline: "Two Buildings. Multiple Revenue Paths.",
    heroDescription: "A rare Route 2 commercial offering combining a four-bay automotive facility with a separate restaurant-style building and drive-thru infrastructure.",
    marketingRemarks: "Located on the main Route 2 corridor near the Route 8 intersection, this mixed-use commercial property includes two buildings across three parcels. The larger building offers four drive-in bays, vehicle lifts, office space, and restrooms. A second restaurant-style building includes a drive-thru window, canopy, and restroom facilities. The broad paved site and two-building configuration create flexibility for complementary businesses, owner-user operations, leasing strategies, or redevelopment. Potential uses remain subject to zoning, permitting, and buyer due diligence.",
    investmentHighlights: [
      "Two commercial buildings across three parcels",
      "Four-bay automotive garage with vehicle lifts",
      "Office space and restrooms within the garage building",
      "Separate restaurant-style building with drive-thru window and canopy",
      "Large paved area supporting parking and circulation",
      "High-visibility Route 2 position near Route 8"
    ],
    useCases: ["Automotive service", "Fleet maintenance", "Restaurant or drive-thru concept", "Two-business owner-user campus", "Commercial leasing", "Redevelopment opportunity"],
    page: "1130-north-chester-street.html",
    assetBase: "assets/1130-north-chester-street",
    hero: "hero.jpg",
    detailFacts: [
      { value: "2", label: "Buildings" },
      { value: "4", label: "Garage Bays" },
      { value: "3", label: "Parcels" }
    ],
    photos: [
      { file: "photo-01.jpg", alt: "Wide site view of both commercial buildings" },
      { file: "photo-02.jpg", alt: "Front elevation of the four-bay garage" },
      { file: "photo-03.jpg", alt: "Garage building and expansive paved parking area" },
      { file: "photo-04.jpg", alt: "Interior vehicle lifts and mezzanine workspace" },
      { file: "photo-05.jpg", alt: "Automotive bay and lift interior" },
      { file: "photo-06.jpg", alt: "Rear of the restaurant-style commercial building" },
      { file: "photo-07.jpg", alt: "Side view of the restaurant-style building and canopy" },
      { file: "photo-08.jpg", alt: "Two-building site configuration" },
      { file: "photo-09.jpg", alt: "Drive-thru canopy and building exterior" },
      { file: "photo-10.jpg", alt: "Canopy view toward the garage building" },
      { file: "photo-11.jpg", alt: "Commercial drive-thru building and paved site" }
    ]
  },

  "3716-hanlin-way": {
    id: "3716-hanlin-way",
    version: "19.9",
    status: "Under Contract",
    featured: true,
    featuredOrder: 2,
    community: "Weirton",
    type: "Residential",
    propertyType: "Single-family residence",
    address: "3716 Hanlin Way",
    cityStateZip: "Weirton, WV 26062",
    price: 309500,
    beds: 4,
    baths: 2.5,
    sqft: "2,306",
    acres: "0.14",
    mls: "5240826",
    style: "Ranch",
    yearBuilt: "1929",
    attachedGarage: "Heated 2-car",
    outdoorSpace: "Covered patio and grilling area",
    laundry: "Lower-level laundry area",
    locationLabel: "Weirton, West Virginia",
    heating: "Forced air",
    cooling: "Central air",
    fireplace: "Gas fireplace",
    summary: "A well-maintained four-bedroom home with a private bedroom wing, finished lower level, heated two-car garage, and covered outdoor living space.",
    headline: "Comfortable Living. Flexible Space. A Place to Feel at Home.",
    heroDescription: "Four bedrooms, two and a half baths, 2,306 finished square feet, a finished lower level, heated two-car garage, and covered patio in Weirton.",
    marketingRemarks: "Welcome to 3716 Hanlin Way, a well-maintained home with a comfortable layout designed for everyday living and entertaining. The main level connects a spacious living room with the kitchen and dining area. A private bedroom wing includes three bedrooms, a full bath, and a convenient half bath. Updated flooring and fixtures complement the home's clean appearance. The finished lower level adds a large recreation room with a gas fireplace, built-in shelving, accent lighting, and additional entertainment space. A full bathroom, laundry area, and flexible room offer options for guests, a home office, hobbies, or storage. The heated, fully insulated two-car garage includes upgraded lighting, an insulated door, a newer opener, and storage above. Outside, a covered patio and grilling area create a comfortable setting for relaxing and gathering.",
    page: "3716-hanlin-way.html",
    assetBase: "assets/3716-hanlin-way",
    hero: "hero.jpg",
    detailFacts: [
      { value: "4", label: "Beds" },
      { value: "2.5", label: "Baths" },
      { value: "2,306", label: "Finished Sq. Ft." }
    ],
    floorPlans: [
      { file: "photo-47.jpg", alt: "Full home floor plan overview" },
      { file: "photo-48.jpg", alt: "Main-level floor plan" },
      { file: "photo-49.jpg", alt: "Lower-level floor plan" }
    ],
    photos: [
      { file: "photo-01.jpg", alt: "3716 Hanlin Way property photo 1" },
      { file: "photo-02.jpg", alt: "3716 Hanlin Way property photo 2" },
      { file: "photo-03.jpg", alt: "3716 Hanlin Way property photo 3" },
      { file: "photo-04.jpg", alt: "3716 Hanlin Way property photo 4" },
      { file: "photo-05.jpg", alt: "3716 Hanlin Way property photo 5" },
      { file: "photo-06.jpg", alt: "3716 Hanlin Way property photo 6" },
      { file: "photo-07.jpg", alt: "3716 Hanlin Way property photo 7" },
      { file: "photo-08.jpg", alt: "3716 Hanlin Way property photo 8" },
      { file: "photo-09.jpg", alt: "3716 Hanlin Way property photo 9" },
      { file: "photo-10.jpg", alt: "3716 Hanlin Way property photo 10" },
      { file: "photo-11.jpg", alt: "3716 Hanlin Way property photo 11" },
      { file: "photo-12.jpg", alt: "3716 Hanlin Way property photo 12" },
      { file: "photo-13.jpg", alt: "3716 Hanlin Way property photo 13" },
      { file: "photo-14.jpg", alt: "3716 Hanlin Way property photo 14" },
      { file: "photo-15.jpg", alt: "3716 Hanlin Way property photo 15" },
      { file: "photo-16.jpg", alt: "3716 Hanlin Way property photo 16" },
      { file: "photo-17.jpg", alt: "3716 Hanlin Way property photo 17" },
      { file: "photo-18.jpg", alt: "3716 Hanlin Way property photo 18" },
      { file: "photo-19.jpg", alt: "3716 Hanlin Way property photo 19" },
      { file: "photo-20.jpg", alt: "3716 Hanlin Way property photo 20" },
      { file: "photo-21.jpg", alt: "3716 Hanlin Way property photo 21" },
      { file: "photo-22.jpg", alt: "3716 Hanlin Way property photo 22" },
      { file: "photo-23.jpg", alt: "3716 Hanlin Way property photo 23" },
      { file: "photo-24.jpg", alt: "3716 Hanlin Way property photo 24" },
      { file: "photo-25.jpg", alt: "3716 Hanlin Way property photo 25" },
      { file: "photo-26.jpg", alt: "3716 Hanlin Way property photo 26" },
      { file: "photo-27.jpg", alt: "3716 Hanlin Way property photo 27" },
      { file: "photo-28.jpg", alt: "3716 Hanlin Way property photo 28" },
      { file: "photo-29.jpg", alt: "3716 Hanlin Way property photo 29" },
      { file: "photo-30.jpg", alt: "3716 Hanlin Way property photo 30" },
      { file: "photo-31.jpg", alt: "3716 Hanlin Way property photo 31" },
      { file: "photo-32.jpg", alt: "3716 Hanlin Way property photo 32" },
      { file: "photo-33.jpg", alt: "3716 Hanlin Way property photo 33" },
      { file: "photo-34.jpg", alt: "3716 Hanlin Way property photo 34" },
      { file: "photo-35.jpg", alt: "3716 Hanlin Way property photo 35" },
      { file: "photo-36.jpg", alt: "3716 Hanlin Way property photo 36" },
      { file: "photo-37.jpg", alt: "3716 Hanlin Way property photo 37" },
      { file: "photo-38.jpg", alt: "3716 Hanlin Way property photo 38" },
      { file: "photo-39.jpg", alt: "3716 Hanlin Way property photo 39" },
      { file: "photo-40.jpg", alt: "3716 Hanlin Way property photo 40" },
      { file: "photo-41.jpg", alt: "3716 Hanlin Way property photo 41" },
      { file: "photo-42.jpg", alt: "3716 Hanlin Way property photo 42" },
      { file: "photo-43.jpg", alt: "3716 Hanlin Way property photo 43" },
      { file: "photo-44.jpg", alt: "3716 Hanlin Way property photo 44" },
      { file: "photo-45.jpg", alt: "3716 Hanlin Way property photo 45" },
      { file: "photo-46.jpg", alt: "3716 Hanlin Way property photo 46" }
    ]
  },

  "43133-old-irondale-road": {
    id: "43133-old-irondale-road",
    version: "20.0",
    status: "Active",
    featured: true,
    featuredOrder: 1,
    community: "Wellsville",
    type: "Residential",
    propertyType: "Single-family residence",
    address: "43133 Old Irondale Road",
    cityStateZip: "Wellsville, OH 43968",
    price: 280000,
    beds: 3,
    baths: 2,
    sqft: "1,654",
    acres: "5.00",
    mls: "5244242",
    style: "Ranch",
    yearBuilt: "1956",
    attachedGarage: "Detached 1-car garage",
    outdoorSpace: "Covered patio, private yard, and countryside views",
    laundry: "Main-level laundry",
    locationLabel: "Wellsville, Ohio",
    heating: "Forced air, oil",
    cooling: "Central air",
    water: "Well",
    sewer: "Septic",
    fireplace: "1 fireplace",
    roof: "Asphalt",
    summary: "A well-maintained three-bedroom ranch offering one-level living, 1,654 square feet, a detached garage, and approximately five acres in Wellsville.",
    headline: "One-Level Living. Five Acres. Room to Make It Your Own.",
    heroDescription: "A three-bedroom, two-bath ranch with 1,654 square feet, central air, custom cabinetry, a detached garage, and approximately five acres.",
    marketingRemarks: "Welcome to 43133 Old Irondale Road in Wellsville, Ohio. Set on approximately five acres, this well-maintained ranch offers 1,654 square feet of convenient one-level living with three bedrooms and two baths. The home features a comfortable, functional floor plan with spacious living areas, custom cabinetry, and central air. The property provides substantial outdoor space along with a detached garage for parking, storage, hobbies, or additional workspace. With its combination of acreage, single-level living, and a well-cared-for interior, the home offers buyers additional space both inside and out. Mineral rights convey with the property.",
    page: "43133-old-irondale-road.html",
    assetBase: "assets/43133-old-irondale-road",
    hero: "hero.jpg",
    detailFacts: [
      { value: "3", label: "Beds" },
      { value: "2", label: "Baths" },
      { value: "5.00", label: "Acres" }
    ],
    floorPlans: [
      { file: "photo-35.jpg", alt: "Floor plan for 43133 Old Irondale Road" }
    ],
    photos: [
      { file: "photo-01.jpg", alt: "43133 Old Irondale Road property photo 1" },
      { file: "photo-02.jpg", alt: "43133 Old Irondale Road property photo 2" },
      { file: "photo-03.jpg", alt: "43133 Old Irondale Road property photo 3" },
      { file: "photo-04.jpg", alt: "43133 Old Irondale Road property photo 4" },
      { file: "photo-05.jpg", alt: "43133 Old Irondale Road property photo 5" },
      { file: "photo-06.jpg", alt: "43133 Old Irondale Road property photo 6" },
      { file: "photo-07.jpg", alt: "43133 Old Irondale Road property photo 7" },
      { file: "photo-08.jpg", alt: "43133 Old Irondale Road property photo 8" },
      { file: "photo-09.jpg", alt: "43133 Old Irondale Road property photo 9" },
      { file: "photo-10.jpg", alt: "43133 Old Irondale Road property photo 10" },
      { file: "photo-11.jpg", alt: "43133 Old Irondale Road property photo 11" },
      { file: "photo-12.jpg", alt: "43133 Old Irondale Road property photo 12" },
      { file: "photo-13.jpg", alt: "43133 Old Irondale Road property photo 13" },
      { file: "photo-14.jpg", alt: "43133 Old Irondale Road property photo 14" },
      { file: "photo-15.jpg", alt: "43133 Old Irondale Road property photo 15" },
      { file: "photo-16.jpg", alt: "43133 Old Irondale Road property photo 16" },
      { file: "photo-17.jpg", alt: "43133 Old Irondale Road property photo 17" },
      { file: "photo-18.jpg", alt: "43133 Old Irondale Road property photo 18" },
      { file: "photo-19.jpg", alt: "43133 Old Irondale Road property photo 19" },
      { file: "photo-20.jpg", alt: "43133 Old Irondale Road property photo 20" },
      { file: "photo-21.jpg", alt: "43133 Old Irondale Road property photo 21" },
      { file: "photo-22.jpg", alt: "43133 Old Irondale Road property photo 22" },
      { file: "photo-23.jpg", alt: "43133 Old Irondale Road property photo 23" },
      { file: "photo-24.jpg", alt: "43133 Old Irondale Road property photo 24" },
      { file: "photo-25.jpg", alt: "43133 Old Irondale Road property photo 25" },
      { file: "photo-26.jpg", alt: "43133 Old Irondale Road property photo 26" },
      { file: "photo-27.jpg", alt: "43133 Old Irondale Road property photo 27" },
      { file: "photo-28.jpg", alt: "43133 Old Irondale Road property photo 28" },
      { file: "photo-29.jpg", alt: "43133 Old Irondale Road property photo 29" },
      { file: "photo-30.jpg", alt: "43133 Old Irondale Road property photo 30" },
      { file: "photo-31.jpg", alt: "43133 Old Irondale Road property photo 31" },
      { file: "photo-32.jpg", alt: "43133 Old Irondale Road property photo 32" },
      { file: "photo-33.jpg", alt: "43133 Old Irondale Road property photo 33" },
      { file: "photo-34.jpg", alt: "43133 Old Irondale Road property photo 34" },
      { file: "photo-35.jpg", alt: "43133 Old Irondale Road property photo 35" }
    ]
  },

  "1938-crawford-avenue": {
    id: "1938-crawford-avenue",
    version: "19.8",
    status: "Under Contract",
    featured: true,
    featuredOrder: 3,
    community: "Weirton",
    type: "Residential",
    propertyType: "Single-family residence",
    address: "1938 Crawford Avenue",
    cityStateZip: "Weirton, WV 26062",
    price: 115000,
    beds: 4,
    baths: 2.5,
    sqft: "1,708",
    finishedBasement: "Approximately 250 sq. ft.",
    totalFinishedArea: "Approximately 1,958 sq. ft.",
    acres: "0.09",
    mls: "5240057",
    style: "Tudor",
    yearBuilt: "1920",
    attachedGarage: "1-car integral",
    outdoorSpace: "Covered front porch and established landscaping",
    laundry: "Lower-level laundry area",
    locationLabel: "Weirton, West Virginia",
    heating: "Forced air",
    cooling: "Wall/window units",
    water: "Public",
    sewer: "Public",
    roof: "Metal",
    summary: "A four-bedroom Tudor-style home with main-floor bedroom options, bathrooms on all three levels, finished lower-level sitting space, a metal roof, and an integral garage.",
    headline: "More Space. More Flexibility. A Layout That Gives You Options.",
    heroDescription: "Four bedrooms, two and a half baths, main-floor living options, finished lower-level bonus space, and classic brick character in Weirton.",
    marketingRemarks: "Welcome to 1938 Crawford Avenue in Weirton, a four-bedroom, two-and-a-half-bath home offering approximately 1,708 square feet of above-grade living space across a versatile floor plan. The main level keeps everyday living within easy reach with two bedrooms, a full bath, living room, dining room, and kitchen. Upstairs, two additional bedrooms and another full bath provide separation and flexibility for guests, a home office, or hobby space. The basement includes an estimated 250 square feet of finished sitting space, a half bath, laundry area, and integral garage. Outside, the brick exterior, metal roof, covered front porch, and established landscaping create a classic and welcoming presence.",
    page: "1938-crawford-avenue.html",
    assetBase: "assets/1938-crawford-avenue",
    hero: "hero.jpg",
    detailFacts: [
      { value: "4", label: "Beds" },
      { value: "2.5", label: "Baths" },
      { value: "1,708", label: "Above-Grade Sq. Ft." }
    ],
    floorPlans: [
      { file: "photo-41.jpg", alt: "Combined floor plan overview for 1938 Crawford Avenue" },
      { file: "photo-42.jpg", alt: "Main living level floor plan" },
      { file: "photo-43.jpg", alt: "Upper bedroom level floor plan" },
      { file: "photo-44.jpg", alt: "Lower level and integral garage floor plan" }
    ],
    photos: Array.from({ length: 40 }, (_, index) => ({
      file: `photo-${String(index + 1).padStart(2, "0")}.jpg`,
      alt: `1938 Crawford Avenue property photo ${index + 1}`
    }))
  }};

(function buildPropertyViews() {
  const formatPrice = (record) => {
    if (record.priceText) return record.priceText;
    if (typeof record.price === "number") {
      return new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD",
        maximumFractionDigits: 0
      }).format(record.price);
    }
    return record.price || "Contact for Price";
  };

  const records = Object.values(window.MASTER_PROPERTIES).map((record) => ({
    ...record,
    photos: record.status === "Under Contract" ? (record.photos || []).slice(0, 12) : (record.photos || []),
    price: formatPrice(record),
    image: record.image || (record.assetBase && record.hero ? `${record.assetBase}/${record.hero}` : "assets/media-fallback.svg")
  }));

  window.LISTINGS_DATA = records;
  window.getMasterProperty = (slug) => records.find((record) => record.id === slug) || null;

  if (window.ACTIVE_PROPERTY_SLUG) {
    window.PROPERTY_DATA = window.getMasterProperty(window.ACTIVE_PROPERTY_SLUG);
  }
})();
